# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'VotingBooth' do
     pod 'SnapKit', '~> 0.15.0'
     pod 'JSONHelper'
     pod 'SIOSocket', '~> 0.2.0'
     pod 'SDWebImage', '~> 3.7.3'
end

